-- Create Client table
CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    prenom VARCHAR(255),
    adresse VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    telephone VARCHAR(255) NOT NULL,
    ice VARCHAR(255),
    if_client VARCHAR(255),
    rc VARCHAR(255)
);

-- Create Roles table
CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- Create App Users table
CREATE TABLE app_users (
    username VARCHAR(255) PRIMARY KEY,
    password VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL
);

-- Create User Roles join table
CREATE TABLE user_roles (
    user_username VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_username, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_username) REFERENCES app_users(username),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- Create Prestations table
CREATE TABLE prestations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL UNIQUE,
    libelle VARCHAR(255) NOT NULL,
    taux_tva DOUBLE PRECISION NOT NULL,
    taux_tr DOUBLE PRECISION NOT NULL,
    compte_comptable VARCHAR(255) NOT NULL
);

-- Create Bulletins table
CREATE TABLE bulletins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_bulletin_metier VARCHAR(255) UNIQUE,
    client_id BIGINT NOT NULL,
    periode_facturation VARCHAR(255),
    statut VARCHAR(255) NOT NULL,
    date_reception TIMESTAMP NOT NULL,
    CONSTRAINT fk_bulletins_client FOREIGN KEY (client_id) REFERENCES client(id)
);

-- Create Lignes Bulletin table
CREATE TABLE lignes_bulletin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulletin_id BIGINT NOT NULL,
    prestation_id BIGINT,
    quantite DOUBLE PRECISION NOT NULL,
    type_terrain VARCHAR(255),
    nature_activite VARCHAR(255),
    categorie VARCHAR(255),
    code_port VARCHAR(255),
    code_activite VARCHAR(255),
    CONSTRAINT fk_lignes_bulletin_bulletin FOREIGN KEY (bulletin_id) REFERENCES bulletins(id)
);

-- Create Facture table
CREATE TABLE facture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero VARCHAR(255) NOT NULL UNIQUE,
    date DATE NOT NULL,
    client_id BIGINT NOT NULL,
    statut VARCHAR(255) NOT NULL,
    montant_ht DOUBLE PRECISION NOT NULL,
    montant_tr DOUBLE PRECISION NOT NULL,
    montant_tva DOUBLE PRECISION NOT NULL,
    montant_ttc DOUBLE PRECISION NOT NULL,
    transmission_statut VARCHAR(255),
    date_transmission TIMESTAMP,
    CONSTRAINT fk_facture_client FOREIGN KEY (client_id) REFERENCES client(id)
);

-- Create Ligne Facture table
CREATE TABLE ligne_facture (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    facture_id BIGINT NOT NULL,
    prestation_id BIGINT NOT NULL,
    quantite DOUBLE PRECISION NOT NULL,
    prix_unitaire DOUBLE PRECISION NOT NULL,
    taux_tva DOUBLE PRECISION NOT NULL,
    montant_ht DOUBLE PRECISION NOT NULL,
    taux_tr DOUBLE PRECISION NOT NULL,
    montant_tr DOUBLE PRECISION NOT NULL,
    montant_tva DOUBLE PRECISION NOT NULL,
    montant_ttc DOUBLE PRECISION NOT NULL,
    CONSTRAINT fk_ligne_facture_facture FOREIGN KEY (facture_id) REFERENCES facture(id),
    CONSTRAINT fk_ligne_facture_prestation FOREIGN KEY (prestation_id) REFERENCES prestations(id)
);

-- Create Audit Log table
CREATE TABLE audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL,
    username VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    details TEXT,
    ip_address VARCHAR(255)
);

-- Create Tarifs tables

-- Tarif Autorisation
CREATE TABLE tarifs_autorisation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestation_id BIGINT NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    montant DOUBLE PRECISION NOT NULL,
    annee_tarif INTEGER NOT NULL,
    annee_debut_revision INTEGER,
    taux_revision DOUBLE PRECISION,
    delai_revision INTEGER,
    actif BOOLEAN NOT NULL,
    CONSTRAINT fk_tarif_autorisation_prestation FOREIGN KEY (prestation_id) REFERENCES prestations(id)
);

-- Tarif Concession
CREATE TABLE tarifs_concession (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestation_id BIGINT NOT NULL,
    type_contrat VARCHAR(255) NOT NULL,
    montant DOUBLE PRECISION NOT NULL,
    annee_tarif INTEGER NOT NULL,
    annee_debut_revision INTEGER,
    taux_revision DOUBLE PRECISION,
    delai_revision INTEGER,
    actif BOOLEAN NOT NULL,
    CONSTRAINT fk_tarif_concession_prestation FOREIGN KEY (prestation_id) REFERENCES prestations(id)
);

-- Tarif Eau Electricite
CREATE TABLE tarifs_eau_electricite (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestation_id BIGINT NOT NULL,
    code_port VARCHAR(255) NOT NULL,
    libelle VARCHAR(255) NOT NULL,
    code_activite VARCHAR(255) NOT NULL,
    tarif_distributeur DOUBLE PRECISION NOT NULL,
    tarif_facture DOUBLE PRECISION NOT NULL,
    annee_tarif INTEGER NOT NULL,
    annee_debut_revision INTEGER,
    taux_revision DOUBLE PRECISION,
    delai_revision INTEGER,
    actif BOOLEAN NOT NULL,
    CONSTRAINT fk_tarif_eau_elec_prestation FOREIGN KEY (prestation_id) REFERENCES prestations(id)
);

-- Tarif OTDP
CREATE TABLE tarifs_otdp (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestation_id BIGINT NOT NULL,
    type_terrain VARCHAR(255) NOT NULL,
    nature_activite VARCHAR(255) NOT NULL,
    categorie VARCHAR(255) NOT NULL,
    unite_base VARCHAR(255),
    montant DOUBLE PRECISION NOT NULL,
    annee_tarif INTEGER NOT NULL,
    annee_debut_revision INTEGER,
    taux_revision DOUBLE PRECISION,
    delai_revision INTEGER,
    actif BOOLEAN NOT NULL,
    CONSTRAINT fk_tarif_otdp_prestation FOREIGN KEY (prestation_id) REFERENCES prestations(id)
);

-- Insert default roles
INSERT INTO roles (name) VALUES ('ROLE_ADMIN');
INSERT INTO roles (name) VALUES ('ROLE_GESTIONNAIRE');
INSERT INTO roles (name) VALUES ('ROLE_CONSULTANT');
